name = "stm32_demo"
description = "A demo program to run on STM32"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
gnat_arm_elf = "*"
astro = "^1.1.1"

[[pins]]
astro = { path='../astro' }

